import Head from 'next/head'
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>moviefolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://i.ibb.co/qDcspxb/fav.png" />
      </Head>

      {/* Header */}
      <Header />
    </div>
  )
}
