import Head from 'next/head'
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";

export default function Home(props) {
  console.log(props);
  return (
    <div>
      <Head>
        <title>moviefolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://i.ibb.co/qDcspxb/fav.png" />
      </Head>

      {/* Header */}
      <Header />
      <Nav />
      <Results results={results}/>

    </div>
  )
}

//Server side render
export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}